---
- name: Dlink  Standard Configuration
  hosts: L2AS
  gather_facts: false
  #  connection: network_cli
     
# Configuring..... 
# Hostname
# Enabling Spanning Tree
# Disabling Telnet
# Disabling HTTP
# Configuring NTP Services
# Creating User

  tasks:
    - name: Dlink  Global Settings
      ios_config:
        lines:
          - snmp-server name {{inventory_hostname}}      
          - spanning-tree global state enable
          - sntp enable
          - sntp server 172.20.2.251
          - sntp interval 60
          - clock timezone + 5 30
          - logging buffered severity debugging write-delay 3
          - logging server 172.20.2.251 severity debugging facility 23 port 514
          - command logging enable  
           
        
      register: print_output

    -  debug: var=print_output

# Configuring...
# Changing ports mode to access
# Confguring Switch-port Security

    - name: Access port configuration
      ios_config:
        parents: interface range ethernet 1/0/1-22
        lines:
           - switchport mode access
           - switchport port-security
           - switchport port-security maximum 1
           - switchport port-security mode permanent
           - switchport port-security violation protect
      
      register: print_output

    -  debug: var=print_output

    - name: shutting down OFC ports
      ios_config:
        parents: interface range ethernet 1/0/25-28
        lines:
           - shutdown

      register: print_output

    -  debug: var=print_output


    - name: Saving Configuration
      ios_command:
       commands:
       - command: 'copy running-config startup-config'
         prompt: 'Destination filename startup-config?'
         answer: 'y'


      register: print_output
    -  debug: var=print_output
