---
- name: Exporting Configuration 
  hosts: L1AS
  become: true
  gather_facts: no
  tasks:
    - name: exporting configuration 
      ios_config:
       backup: yes
       backup_options:
        filename: "{{inventory_hostname}}"
        dir_path: configfiles
        

