---
- name: Dlink Configuration
  hosts: all
  gather_facts: false

  tasks:

    - name: Configuring 7989-L1-as13
      include_tasks: l1-as13.yml
      run_once: true
      when: inventory_hostname == '7989-l1-as13'
      

    - name: Configuring 7989-l1-as14  
      include_tasks: l1-as14.yml
      run_once: true
      when: inventory_hostname == '7989-l1-as14'
    
    - name: Configuring 7989-l1-as15  
      include_tasks: l1-as15.yml
      run_once: true
      when: inventory_hostname == '7989-l1-as15'
              
      
      register: print_output

    -  debug: var=print_output

    - name: run commands that require answering a prompt
      ios_command:
       commands:
       - command: 'copy running-config startup-config'
         prompt: 'Destination filename startup-config?'
         answer: 'y'


      register: print_output
    -  debug: var=print_output
